aws:
  access-key: AKIA5HZX4IVBUOLOEIG5
  secret-key: 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
  region: us-east-2
  cognito:
    user-pool-id: us-east-2_tFsV0yHdD
    app-client-id: 6gp2mgqvto9ee425v0t471gnj2
    #app-client-secret: 1b6omphrdbmtd1cg2qob6httc9mb9lklb61juvt1u1rd19tu5h9c
